[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate",
  "pip install --no-cache-dir --break-system-packages -r requirements.txt"
]

[phases.start]
cmd = "source venv/bin/activate && python bot.py"
